### ISSUE TITLE
Week start

### ISSUE THREAD

**Issue by cg505** [kotct/docket-old#20] opened 2014-01-01 17:19 UTC
There are a few proposals here:
1. The week should not start on Sunday. There is no reason to have the week start on Sunday, the weekend should be kept next to each other, the physical docket doesn't start on Sunday.
2. The week should start on Monday. This is the way the docket does it, and there are many people who generally consider that the start of the week, regardless of application (such as me).
3. The week should start on Saturday. While almost nobody would say the week actually starts on Saturday, this solution keeps the weekend together. The other important thing is that looking at the docket on Saturday allows you to look forward on the upcoming week.
4. The week ends on Sunday and starts on either Monday or today if it's Friday, Saturday, or Sunday. This allows you to look forward on upcoming assignments in the next week during the weekend, but still allows you to see your events for the current weekend. It also (in a sense) starts the week on Monday, which is a good idea, especially because it doesn't clutter the top of the docket with weekend days which are used only for events.

Which combination of these do you think is best?

**Comment by Sammidysam** [comment] 2014-01-01 17:34
1 and 2.  Though, maybe we could add two week views: one that starts on Monday and one that starts on today.

Based on what #23 mentions, we can just keep one week view and let users configure what day it starts on.

**Comment by rye** [comment] 2014-01-01 17:36
As it stands now, the week starts on Sunday because DateTime's [wday](http://ruby-doc.org/stdlib-2.1.0/libdoc/date/rdoc/Date.html#method-i-wday) method (which is what we use for day numbering) defaults to having Sunday as zero.

We could very simply express stuff differently and start the week on Monday, as that is both [ISO compliant](http://en.wikipedia.org/wiki/ISO_8601#Week_dates) and the way it is in the paper docket as it stands now.

I like the idea of starting on Saturday, and your reasoning makes a lot of sense, but we could just include a "next week" thing with the "upcoming assignments" suggestion we discussed earlier.

I think the important thing, however, is that we need to work heavily on is user configuration; many of these things we're discussing make sense to be configurable by the user, and this idea is no exception.

**Comment by rye** [comment] 2014-01-01 17:38
I'm going to make a new issue for ~~this~~ user configuration. (gah, pronouns)

**Comment by Sammidysam** [comment] 2014-01-01 17:41
That seems redundant, considering that it will be a semi-duplicate of https://github.com/kotct/docket/issues/21.  Not a full duplicate, but they pertain to the same subject.

**Comment by cg505** [comment] 2014-01-02 06:52
You both seem to have rejected #<span class="stop-gfm-issue-linker">4</span>, which is personally my favorite option. Why is that?

**Comment by rye** [comment] 2014-01-02 13:39
Once again, if we add User Configuration, we could add this option.

**Comment by rye** [comment] 2014-01-15 18:25
So it looks to me like (since I've gotten no feedback) we would probably want to look into the user configuration.

I think another suggestion would work. In addition to all of the four items that @cg505 listed, we may also want to consider setting up two additional options. The first would be that the week displayed starts with the current day. The other that I can think of is where the week that is displayed starts with the following day from the current day.

I would say, also, that we should include options for the week starting on every day.

So here is a boiled-down collection of ideas:
1. The week starts on Monday
2. The week starts on Tuesday
3. The week starts on Wednesday
4. The week starts on Thursday
5. The week starts on Friday
6. The week is either the current week (starting on one of the above) or the remainder of this week plus next week if it is currently the weekend. (This description needs to be simplified, methinks)
7. The week starts on the current day
8. The week starts on the day after the current day

For the purposes of this list, "the week" refers to the array of days that is returned by a new function (specified below).

In order to implement this, I think that we should consider splitting this specific customization into multiple components. For example, we have multiple "week start" days (e.g. Monday, Tuesday, ..., Today, Tomorrow), and we also have multiple week selection styles (e.g. the classical 7-day week, and the extended week), so we could consider implementing those as two separate fields in the "configuration" table.

A function that would, then, be written, would return an array of days that are the days of the week that will be displayed. This would contain all of the various styling things and would allow us to make things much more dynamic, yet simple. This function would take a given user and would find the configuration associated with them, then spit out their things.

**Comment by Sammidysam** [comment] 2014-01-18 03:04
I agreed that using configuration for this was a good route, but forgot to reply---sorry.

We will, therefore, want a "Week Start" option that contains all of that.  It will have options of all of the days of the week, plus other options that were listed above.

**Comment by rye** [comment] 2014-01-18 11:23
And, considering that it's been basically decided that user configuration is a `v0.3.0`-only thing, I'm not going to implement stuff in `v0.2.0` just to rewrite it.

**Comment by Sammidysam** [comment] 2014-01-18 19:01
That is a good idea.  Speaking of user configuration, are we going to revert the work towards that that were added to 0.2.0, or what?  I.e. what is our plan with dealing what that?

**Closed as completed** 2015-11-25 23:31 UTC
Labels: enhancement, deferred
